// import { TColor } from "./type.d";

const Color: TColor = {
  colorPrimary: "#3b82f6",
  colorText: "#171717",
  colorTextDesc: "#a3a3a3",
  colorTextLight: "#d4d4d4",
  colorTextPlaceholder: "#e5e5e5",
  colorTextDisabled: "#737373",
  colorTextError: "#ef4444",
  colorTextWarning: "#fb923c",
  colorTextSuccess: "#22c55e",
  colorTextInfo: "#3b82f6",
  colorTextHover: "#404040",
  colorTextActive: "#3b82f6",
  colorTextFocus: "#93c5fd",
  colorBgLayout: "#f1f5f9",
  colorBgComponent: "#ffffff",
  colorBgSecondary: "#f3f4f6",
  colorBgContainer: "#fafafa",
  colorBgDesc: "#f5f5f5",
  colorBgLight: "#fafafa",
  colorBgPlaceholder: "#e5e5e5",
  colorBgDisabled: "#e5e5e5",
  colorBgError: "#fecaca",
  colorBgWarning: "#fed7aa",
  colorBgSuccess: "#bbf7d0",
  colorBgInfo: "#bfdbfe",
  colorBgHover: "#ffffff",
  colorBgActive: "#f3f4f6",
  colorBgFocus: "#f3f4f6",
  colorBorder: "#cbd5e1",
  colorBorderDisabled: "#94a3b8",
  colorBorderError: "#ef4444",
  colorBorderWarning: "#fb923c",
  colorBorderSuccess: "#22c55e",
  colorBorderInfo: "#3b82f6",
  colorBorderHover: "#bfdbfe",
  colorBorderActive: "#3b82f6",
  colorBorderFocus: "#93c5fd",
  colorShadow: "#f5f5f5",
  colorShadowHover: "#fafafa",
  colorShadowActive: "#f5f5f5",
  colorShadowFocus: "#fafafa",
};

/** 样式尺寸 */
const Size = {
  sizeFont: "14px",
  sizeFontTitle: "18px",
  sizeFontDesc: "14px",
  sizeFontP: "14px",
  sizeFontH6: "14px",
  sizeFontH5: "16px",
  sizeFontH4: "18px",
  sizeFontH3: "20px",
  sizeFontH2: "24px",
  sizeFontH1: "32px",
  sizeMargin: "16px",
  sizeMarginSmall: "8px",
  sizeMarginLarge: "24px",
  sizePadding: "12px",
  sizePaddingSmall: "4px",
  sizePaddingLarge: "20px",
  sizeBorderWidth: "3px",
  sizeBorderWidthSmall: "1px",
  sizeBorderWidthLarge: "8px",
  sizeBorderRadius: "4px",
  sizeBorderRadiusSmall: "2px",
  sizeBorderRadiusLarge: "8px",
  sizeFontWeight: "500",
  sizeFontWeightSmall: "300",
  sizeFontWeightLarge: "800",
};

const Style = {
  font: "-apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, 'Noto Sans', sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji'",
};

module.exports = {
  ...Color,
  ...Size,
  ...Style,
};
